### ISSUE TITLE
npm WARN cleanup Failed to remove some directories

### ISSUE THREAD

**Issue by Jagadeeshftw** [RosarioB/ethereum-simple-contract#1]
JagadeeshB@Jagadeesh MINGW64 ~/Downloads/ethereum-simple-contract-simple_contract/ethereum-simple-contract-simple_contract
$ npm install
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\JagadeeshB\\Downloads\\ethereum-simple-contract-simple_contract\\ethereum-simple-contract-simple_contract\\node_modules\\ganache',
npm WARN cleanup     [Error: EPERM: operation not permitted, lstat 'C:\Users\JagadeeshB\Downloads\ethereum-simple-contract-simple_contract\ethereum-simple-contract-simple_contract\node_modules\ganache\dist\web\ganache.min.js'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'lstat',
npm WARN cleanup       path: 'C:\\Users\\JagadeeshB\\Downloads\\ethereum-simple-contract-simple_contract\\ethereum-simple-contract-simple_contract\\node_modules\\ganache\\dist\\web\\ganache.min.js'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\JagadeeshB\\Downloads\\ethereum-simple-contract-simple_contract\\ethereum-simple-contract-simple_contract\\node_modules\\ethereumjs-vm',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\JagadeeshB\Downloads\ethereum-simple-contract-simple_contract\ethereum-simple-contract-simple_contract\node_modules\ethereumjs-vm'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\JagadeeshB\\Downloads\\ethereum-simple-contract-simple_contract\\ethereum-simple-contract-simple_contract\\node_modules\\ethereumjs-vm'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\JagadeeshB\\Downloads\\ethereum-simple-contract-simple_contract\\ethereum-simple-contract-simple_contract\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, lstat 'C:\Users\JagadeeshB\Downloads\ethereum-simple-contract-simple_contract\ethereum-simple-contract-simple_contract\node_modules\ganache\dist\web\ganache.min.js'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'lstat',
npm WARN cleanup       path: 'C:\\Users\\JagadeeshB\\Downloads\\ethereum-simple-contract-simple_contract\\ethereum-simple-contract-simple_contract\\node_modules\\ganache\\dist\\web\\ganache.min.js'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code ENOTEMPTY
npm ERR! syscall rmdir
npm ERR! path C:\Users\JagadeeshB\Downloads\ethereum-simple-contract-simple_contract\ethereum-simple-contract-simple_contract\node_modules\ganache\dist\web
npm ERR! errno -4051
npm ERR! ENOTEMPTY: directory not empty, rmdir 'C:\Users\JagadeeshB\Downloads\ethereum-simple-contract-simple_contract\ethereum-simple-contract-simple_contract\node_modules\ganache\dist\web'

npm ERR! A complete log of this run can be found in: C:\Users\JagadeeshB\AppData\Local\npm-cache\_logs\2024-04-10T08_28_15_837Z-debug-0.log

**Comment by RosarioB** [comment]
Hello Jagadeeshftw,
thank you for opening this issue. I have tried to npm install the code and I have not experienced your issue. However the package [@truffle/hdwallet-provider](https://www.npmjs.com/package/@truffle/hdwallet-provider) has been deprecated so to learn how to develop smart contract I suggest you to use Hardhat. 

You can check out this [repository](https://github.com/RosarioB/basic_hardhat_ethereum) where there is a repository using Hardhat to develop a simple smart contract. The tutorial to create this repository can be found on [Youtube](https://youtu.be/gCFqxdOliTQ?si=wSZ7FiUR5B_4FNbm) and also on [Medium](https://medium.com/coinmonks/effortless-smart-contract-development-with-hardhat-on-ethereum-b7728705f2b8).

**Comment by rosarioborgesi** [comment]
Hello Jagadeeshftw, 
I was unable to reproduce the issue on my machine as it's working fine. It seems that you have some permissions issues on some directories.
